### ISSUE TITLE
Where is config file

### ISSUE THREAD

**Issue by shahidch85** [ShadowLNC/cpanel_dns#1]
hello, 
I think you forget to include config.ini file?
$config = parse_ini_file("config");

**Comment by ShadowLNC** [comment]
Hi,

In future, please specify a filename and line number when you put code here, it means I don't have to search for it (and if it appears more than once, I know which one you are referring to). Thanks! :)

The purpose of a config file is to store settings, usernames, passwords, etc. - these should NEVER be published to the internet. If I hard-coded it in `dns_update.php`, Git would log all my passwords, so instead I put it in a config file - this is why my `.gitignore` file specifically lists the file `config` (not `config.ini`) so that Git won't track the file, and I won't accidentally upload my passwords to GitHub. So no, I didn't forget - I deliberately omitted my config file.

You can observe the variables required in the `config` file by looking in the `dns_update.php` file for lines which access the `$config` array. [Per the PHP docs](https://secure.php.net/manual/en/function.parse-ini-file.php), the syntax is the same as the [`php.ini` PHP configuration syntax](https://secure.php.net/manual/en/configuration.file.php).

Having said all this, I understand the need for an *example* config file for ease of use, and so I have added one to the repository. I have also changed the config file name to make it clear that no extension should be appended to the filename when making the config file (i.e. `parse_ini_file("config")` looks for `config`, *not* `config.ini`).

I've not tested these changes, as I do not currently have a PHP installation available, but if there are issues, please reply to this thread.

**Comment by shahidch85** [comment]
Hello,
First of all sorry for not mentioning file name and line number i it...
I thought there are only two file and that line is at the top you may
remember where it is...

Anyways! I 100% agreed with you but in this case we normally rname a
setting file like config_sample.ini with only declaraction of setting
variables with default value so that our passwords etc remain save...
Just like wordpress and you have done this now...

I have checked and it is working fine thanks !
Once again Thanks for sharing it...
